[package]
name = "aspecky/profileservice"
version = "1.0.5"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "loleri's ProfileService but fully typed"
authors = ["loleris", "aspecky"]

